# Generated by Django 6.0.2 on 2026-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0002_reservation_booking_id_reservation_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Beverages', 'Beverages')], max_length=50)),
                ('restaurantImage', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('is_in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
