# Generated by Django 6.0.2 on 2026-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0002_fooditem_restaurant_order_delivery_orderdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='restaurantImage',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
