# Generated by Django 6.0.2 on 2026-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0004_contactmessage_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
    ]
