# Generated by Django 6.0.2 on 2026-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0004_reservation_amount_alter_menuitem_table_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
