# Generated by Django 6.0.2 on 2026-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0005_reservation_address_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cost_for_two',
            field=models.IntegerField(blank=True, default=0, help_text='Average cost for two people', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, help_text='e.g. Continental, North Indian', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
