# Generated by Django 6.0.2 on 2026-04-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0006_restaurant_address_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
