# Generated by Django 6.0.2 on 2026-03-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0006_tablebooking_delete_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table='ContactMessage',
        ),
        migrations.AlterModelTable(
            name='tablebooking',
            table='TableBooking',
        ),
    ]
