# Generated by Django 6.0.2 on 2026-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0009_alter_fooditem_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
