# Generated by Django 6.0.2 on 2026-04-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0012_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
